version: '3'

services:
  mariadb-docker-container:
    image: mariadb:latest
    networks:
      - app-network
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=blog
      - MYSQL_PASSWORD=root
    volumes:
      - /data/mysql
  spring-boot-app-hybrid:
    build: .
    networks:
      - app-network
    depends_on:
      - mariadb-docker-container
    ports:
      - 8080:8080
    volumes:
      - /data/spring-boot-app-hybrid
    restart: on-failure
networks:
  app-network: